language: java
jdk:
- openjdk6
before_install:
# First icy dependies
- wget http://www.icy.bioimageanalysis.org/downloadIcy/icy.zip && unzip icy.zip -d icy && rm icy.zip
- mkdir lib
- mv icy/icy.jar lib/
- mv icy/lib/bioformats.jar lib/
- mv icy/plugins/adufour/blocks/Blocks.jar lib/
- mv icy/plugins/adufour/ezplug/EzPlug.jar lib/
- mv icy/plugins/adufour/protocols/Protocols.jar lib/
# Then build TiPi.jar
- git clone --quiet --branch=develop https://github.com/emmt/TiPi.git
- cd TiPi && wget --no-check-certificate http://mitiv.univ-lyon1.fr/TiPi.zip && unzip TiPi.zip && rm TiPi.zip
- ant build && ant build-jar
- mv lib/TiPi.jar ../lib && cd ..
script:
- ant build
- ant doc > /dev/null
after_success:
- git config --global user.email "eric.thiebaut@univ-lyon1.fr"
- git config --global user.name "emmt"
- git config --global push.default matching
- git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/emmt/${PROJECT}
- cp -r doc/* ${PROJECT}
- cd ${PROJECT} && git add * && git commit -am "Doc update" && (git push 2> /dev/null)
env:
  global:
  - secure: G0VNj4mO734iePeYNDA0aqYy2mid4dBTEeupwmPEoGEf6yVMYgPrOLvYA0gJYD5MrUMZJ50tFIWWc9rWqsk8CTXCy8a3sAapQZma5TsggrnGOv6IK2emEHx9Znj4kdRRpX3MdxZhLwVTszUkejtoUOmAS4EOtUub4Ky7CUq0WJs=
  - PROJECT=tipi4icy
