language: java
jdk:
- openjdk8

before_script:
- git config --global user.email "ferreol.soulez@univ-lyon1.fr"
- git config --global user.name "ferreolS"
# First icy and dependencies
- wget https://github.com/Icy-imaging/Icy-App/archive/release.zip && unzip release.zip -d icy && rm release.zip
- wget https://github.com/FerreolS/IcyHLPluginInstaller/archive/jar.zip 
- unzip jar.zip 
- mv IcyHLPluginInstaller-jar/IcyHLPluginInstaller.jar icy/plugins/. 
- cd icy 
- java -jar icy.jar -hl -x plugins.ferreol.icyhlplugininstaller.IcyHLPluginInstaller plugins.adufour.ezplug.EzPlug 
- cd ..
- mkdir lib
- mkdir bin
- mv icy/icy.jar lib/
- mv icy/lib/bioformats.jar lib/
- mv icy/plugins/adufour/blocks/Blocks.jar lib/
- mv icy/plugins/adufour/ezplug/EzPlug.jar lib/
- mv icy/plugins/adufour/protocols/Protocols.jar lib/
# prepare for build
- git clone --quiet --branch=master https://github.com/emmt/TiPi.git
- cd TiPi && ant build && ant tipi-sdk
- mv TiPi.zip ../ && cd ..
- cp -r TiPi/lib/* lib/ 
# Then build microtipi
- git clone --quiet --branch=master https://github.com/FerreolS/microTiPi.git
- mkdir src-doc src-epidemic
- cp -r microTiPi/src/microTiPi src-doc
- mv microTiPi/src/microTiPi src-epidemic
- rm -rf doc
- git clone https://github.com/FerreolS/${PROJECT} doc
- cd doc
- git symbolic-ref HEAD refs/heads/gh-pages
- rm .git/index
- git clean -fdx
- cd ..
- rm -rf jar
- git clone https://github.com/FerreolS/${PROJECT} jar
- cd jar
- git symbolic-ref HEAD refs/heads/jars
- rm .git/index
- git clean -fdx
- cd ..


script:
- ant simpledemic
- ant epidemic
- ant doc > /dev/null

after_success:
- cd doc
- git add *
- git commit -a -m "Add Doc"
- git push --force https://${GH_TOKEN}@github.com/FerreolS/${PROJECT} gh-pages
- cd ..

- cp -r docker jar/.
- cp -r README.md jar/.
- cd jar
- git add *
- git commit -a -m "Jar update"
- git push --force https://${GH_TOKEN}@github.com/FerreolS/${PROJECT} jars

env:
  global:
  - PROJECT=tipi4icy
