language: java
jdk:
- oraclejdk7
before_install:
# First icy dependies
- wget http://www.icy.bioimageanalysis.org/downloadIcy/icy.zip && unzip icy.zip -d icy && rm icy.zip
- wget https://github.com/FerreolS/IcyHLPluginInstaller/archive/jar.zip 
- unzip jar.zip 
- mv IcyHLPluginInstaller-jar/IcyHLPluginInstaller.jar icy/plugins/. 
- cd icy 
- java -jar icy.jar -hl -x plugins.ferreol.icyhlplugininstaller.IcyHLPluginInstaller plugins.adufour.ezplug.EzPlug 
- cd ..
- mkdir lib
- mkdir bin
- mv icy/icy.jar lib/
- mv icy/lib/bioformats.jar lib/
- mv icy/plugins/adufour/blocks/Blocks.jar lib/
- mv icy/plugins/adufour/ezplug/EzPlug.jar lib/
- mv icy/plugins/adufour/protocols/Protocols.jar lib/
# prepare for build
- git clone --quiet --branch=ferreol-devel https://github.com/emmt/TiPi.git
- cd TiPi && ant build && ant tipi-sdk
- mv TiPi.zip ../ && cd ..
- cp -r TiPi/lib/* lib/ 
# Then build microtipi
- git clone --quiet --branch=master https://github.com/FerreolS/microTiPi.git
- mv microTiPi/src/microTiPi src-epidemic

script:
- ant simpledemic
- ant epidemic
- ant doc > /dev/null
after_success:
- git config --global user.email "eric.thiebaut@univ-lyon1.fr"
- git config --global user.name "emmt"
- git config --global push.default matching
- git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/emmt/${PROJECT}
- cp -r doc/* ${PROJECT}
- cd ${PROJECT} && git add * && git commit -am "Doc update" && (git push 2> /dev/null) 
- cd .. && rm -rf ${PROJECT}
- git clone  --branch=jars https://${GH_TOKEN}@github.com/emmt/${PROJECT}
- cp -r jar/* ${PROJECT}
- cd ${PROJECT} && git add * && git commit -am "Jar update" && (git push 2> /dev/null) 

env:
  global:
  - secure: G0VNj4mO734iePeYNDA0aqYy2mid4dBTEeupwmPEoGEf6yVMYgPrOLvYA0gJYD5MrUMZJ50tFIWWc9rWqsk8CTXCy8a3sAapQZma5TsggrnGOv6IK2emEHx9Znj4kdRRpX3MdxZhLwVTszUkejtoUOmAS4EOtUub4Ky7CUq0WJs=
  - PROJECT=tipi4icy
