name: docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
on:
  push:
    branches: [ master ]
  schedule:
  - cron: "0 15 17 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push icy:bare
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Icy/bare/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/icy:bare
      -
        name: Build and push icy:full
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Icy/full/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/icy:full
      -
        name: Build and push icy:latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Icy/latest/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/icy:latest
      -
        name: Build and push tipisdk:latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/TiPiSDK/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tipisdk:latest
      -
        name: Build and push simpledemic:latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/simpledemic/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simpledemic:latest
      -
        name: Build and push epidemic:latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/epidemic/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/epidemic:latest
